### ISSUE TITLE
Why is warnings(String key, int type) parameter "type" an integer?

### ISSUE THREAD

**Issue by Joanes-Iri** [Astrotag/CSCU9P6-Group-Assignment#35]
While doing a test for warnings() in Permit_list I realized that warnings() doesn't really need an integer to tell it to delete a warning or not. 

- We could either use a boolean that could be true for adding and false for deleting

- Use parameter type to add whatever the number is. There will be checks to see if current warnings are above 3 or 0

**Comment by RyanKennedy0** [comment]
I do agree that this probably isnt the best way to do it from a design point of view. I would say the best way for us to do this is either keep it as an int for flagging the type or the boolean option. I would advise against us using the second suggestion because as far as I am aware you are only meant to be able to issue one warning at a time.

**Comment by Astrotag** [comment]
I was literally just typing on this. That was strange Ryan. 

I am not sure how else we could do it. If we keep the current setup that we know works then it's fine but I do agree there is probably a better way of doing it.

**Comment by RyanKennedy0** [comment]
Great minds think alike I guess Greig haha.

Yeah because it functions as intended, I say we just leave it as is even if there is a more efficient or correct way of doing it.
